%%% CODE CREATED BY J. BELLINGHAM, UNIVERSITY OF WOLLONGONG %%%
% Generate random polygon from lines given starting point.
% polygon form is nx4 where n is the number of lines. 
% For each row index 1 and 2 and index 3 and 4 represent point 1 and point 2 respectively.
% linesRemJoined is a structure with 1x2 matrixs, point1 and point2  
% pt is the index to the starting point as generated by unassignedPoint 

function [polygon] = generatePolygon(linesRemJoined, pt)
    % Initiations
    p2 = 0;
    start = pt;
    polygon = [];
    % Repeates until finishing point of added line is back at the starting
    % point
    while p2 ~= linesRemJoined(start).point1
        p1 = linesRemJoined(pt).point1;
        p2 = linesRemJoined(pt).point2;
        random = 360;
        % Pick which route to take, wont pick current line
            for comp = 1:length(linesRemJoined)
            if comp ~= pt
                % Only picks next line that joins to current line
                if linesRemJoined(comp).point1 == p2
                    % Unconventionsal way to choose random line
                    numb = randi([1 359],1,1);
                    if (numb < random)
                        random = numb;
                        next = comp;
                    end
                % If chosen line joined from point 2
                elseif linesRemJoined(comp).point2 == p2
                    store = linesRemJoined(comp).point2;
                    linesRemJoined(comp).point2 = linesRemJoined(comp).point1;
                    linesRemJoined(comp).point1 = store;
                    numb = randi([1 359],1,1);
                    if numb < random
                        random = numb;
                        next = comp;
                    end
                end
            end   
        end
        % Move to next point and save line to polygon
        pt = next;
        polygon = [polygon ; p1 , p2];      
    end   
end
